name: Closed Issue Message
on:
  issues:
    types: [closed]

permissions:
  contents: read

jobs:
  auto_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: aws-actions/closed-issue-message@36b7048ea77bb834d16e7a7c5b5471ac767a4ca1 # v1.0.0
        with:
          # These inputs are both required
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            ### ⚠️ COMMENT VISIBILITY WARNING ⚠️
            Comments on closed issues are hard for our team to see.
            If you need more assistance, please either tag a team member or open a new issue that references this one.
            If you wish to keep having a conversation with other community members under this issue feel free to do so.