name: Dispatch analytics

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'

permissions:
  id-token: write
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  dispatch_token:
    if: github.repository == 'aws-powertools/powertools-lambda-typescript'
    concurrency:
      group: analytics
    runs-on: ubuntu-latest
    environment: analytics
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@04b98b3f9e85f563fb061be8751a0352327246b0 # v3.0.1
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ANALYTICS_ROLE_ARN }}
          mask-aws-account-id: true

      - name: Invoke Lambda function
        run: |
          payload=$(echo -n '{"githubToken": "${{ secrets.GITHUB_TOKEN }}"}' | base64)
          aws lambda invoke \
            --function-name ${{ secrets.AWS_ANALYTICS_DISPATCHER_ARN }} \
            --payload "$payload" response.json
          cat response.json
