name: On PR merge

on:
  workflow_run:
    workflows: ["Record PR details"]
    types:
      - completed

concurrency:
  group: on-merge-to-main

permissions:
  contents: read

jobs:
  get_pr_details:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/reusable_export_pr_details.yml
    with:
      record_pr_workflow_id: ${{ github.event.workflow_run.id }}
      workflow_origin: ${{ github.event.repository.full_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  run-unit-tests:
    needs: get_pr_details
    if: ${{ needs.get_pr_details.outputs.prIsMerged == 'true' }}
    uses: ./.github/workflows/reusable-run-linting-check-and-unit-tests.yml
  update-release-draft:
    permissions:
      contents: write
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: Update release draft
        uses: release-drafter/release-drafter@569eb7ee3a85817ab916c8f8ff03a5bd96c9c83e # v5.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release_label_on_merge:
    permissions:
      pull-requests: read
      contents: write
    needs: [get_pr_details, update-release-draft]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: "Label PR related issue for release"
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          PR_NUMBER: ${{ needs.get_pr_details.outputs.prNumber }}
          PR_BODY: ${{ needs.get_pr_details.outputs.prBody }}
          PR_IS_MERGED: ${{ needs.get_pr_details.outputs.prIsMerged }}
          PR_AUTHOR: ${{ needs.get_pr_details.outputs.prAuthor }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/scripts/label_related_issue.js')
            await script({github, context, core})
