name: Post Release

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      versionNumber:
        required: true
        type: string
        description: "If running this manually please insert a version number that corresponds to the latest published in the GitHub releases (i.e. v1.1.1)"
  # Or triggered as result of a release
  release:
    types: [released]

permissions:
  contents: read

jobs:
  post_release:
    permissions:
      contents: read
      issues: write
      discussions: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ inputs.versionNumber }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: Get release version
        run: |
          # The code below does the following:
          # 1. If the workflow was triggered manually, it will use the version number provided by the user
          # 2. If the workflow was triggered by a release, it will use the version number of the release
          if [ -z "$RELEASE_VERSION" ]; then
            export RELEASE_VERSION=$(git describe --tags --abbrev=0)
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Update issues related to release
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const post_release = require('.github/scripts/post_release.js')
            await post_release({github, context, core})