name: Deploy layer to all regions

permissions:
  id-token: write
  contents: write
  pages: write

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      latest_published_version:
        description: "Latest npm published version to rebuild corresponding layer for, e.g. 1.0.2"
        default: "1.0.2"
        required: true

  workflow_call:
    inputs:
      latest_published_version:
        type: string
        description: "Latest npm published version to rebuild latest docs for, e.g. 2.0.0, 2.0.0a1 (pre-release)"
        required: true
      pre_release:
        description: "Publishes documentation using a pre-release tag (2.0.0a1)."
        default: false
        type: boolean
        required: false

jobs:
  # Build layer by running cdk synth in layer-publisher directory and uploading cdk.out for deployment
  build-layer:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "20"
      - name: Setup dependencies
        uses: ./.github/actions/cached-node-modules
      - name: CDK build
        run: npm run cdk -w layers -- synth --context PowertoolsPackageVersion=${{ inputs.latest_published_version }} -o cdk.out
      - name: Zip output
        run: zip -r cdk.out.zip layers/cdk.out
      - name: Archive CDK artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: cdk-layer-artifact
          path: cdk.out.zip

  # Deploy layer to all regions in beta account
  deploy-beta:
    needs:
      - build-layer
    uses: ./.github/workflows/reusable_deploy_layer_stack.yml
    with:
      stage: "BETA"
      artifact-name: "cdk-layer-artifact"
      latest_published_version: ${{ inputs.latest_published_version }}
    secrets:
      target-account-role: ${{ secrets.AWS_LAYERS_BETA_ROLE_ARN }}

  # Deploy layer to all regions in prod account
  deploy-prod:
    needs:
      - deploy-beta
    uses: ./.github/workflows/reusable_deploy_layer_stack.yml
    with:
      stage: "PROD"
      artifact-name: "cdk-layer-artifact"
      latest_published_version: ${{ inputs.latest_published_version }}
    secrets:
      target-account-role: ${{ secrets.AWS_LAYERS_PROD_ROLE_ARN }}

  prepare_docs_alias:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      DOCS_ALIAS: ${{ steps.set-alias.outputs.DOCS_ALIAS }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Set docs alias
        id: set-alias
        run: |
          DOCS_ALIAS=latest
          if [[ "${{ inputs.pre_release }}" == true ]] ; then
            DOCS_ALIAS=alpha
          fi
          echo DOCS_ALIAS="$DOCS_ALIAS" >> "$GITHUB_OUTPUT"

  release-docs:
    needs: [ deploy-prod, prepare_docs_alias ]
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/reusable-publish-docs.yml
    with:
      version: ${{ inputs.latest_published_version }}
      alias: ${{ needs.prepare_docs_alias.outputs.DOCS_ALIAS }}
      detached_mode: true
