name: Update Layer ARN Docs

on:
  workflow_call:
    inputs:
      latest_published_version:
        description: "Latest NPM published version to rebuild latest docs for, e.g. 1.5.1"
        type: string
        required: true

permissions:
  contents: write

env:
  BRANCH: main

jobs:
  publish_layer_arn:
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent race-condition and inconsistencies with changelog push
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout repository # reusable workflows start clean, so we need to checkout again
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
        with:
          fetch-depth: 0
      - name: Git client setup and refresh tip
        run: |
          git config user.name "Release bot[bot]"
          git config user.email "aws-devax-open-source@amazon.com"
          git config pull.rebase true
          git config remote.origin.url >&- || git remote add origin https://github.com/"${origin}" # Git Detached mode (release notes) doesn't have origin
          git pull origin "${BRANCH}"
      - name: Download CDK layer artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: cdk-layer-stack
          path: cdk-layer-stack/
      - name: Replace layer versions in documentation
        run: |
          ls -la cdk-layer-stack/
          ./.github/scripts/update_layer_arn.sh cdk-layer-stack
      - name: Update documentation in trunk
        run: |
          HAS_CHANGE=$(git status --porcelain)
          test -z "${HAS_CHANGE}" && echo "Nothing to update" && exit 0
          git add docs/index.md
          git commit -m "chore: update layer ARN on documentation"
          git pull origin "${BRANCH}" # prevents concurrent branch update failing push
          git push origin HEAD:refs/heads/"${BRANCH}"
