name: Run unit tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-linting-check-and-unit-tests-on-utilities:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        version: [16, 18, 20]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: Setup NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Setup dependencies
        uses: ./.github/actions/cached-node-modules
        with:
          nodeVersion: ${{ matrix.version }}
      - name: Run linting
        run: npm run lint -w packages/commons -w packages/logger -w packages/tracer -w packages/metrics -w packages/parameters -w packages/idempotency -w packages/batch
      - name: Run unit tests
        run: npm t -w packages/commons -w packages/logger -w packages/tracer -w packages/metrics -w packages/parameters -w packages/idempotency -w packages/batch
  check-examples:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        example: ["sam", "cdk"]
      fail-fast: false
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: Setup NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: ./.github/actions/cached-node-modules
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm t
  check-layer-publisher:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: Setup NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: ./.github/actions/cached-node-modules
      - name: Run linting
        run: npm run lint -w layers
      - name: Run tests
        run: npm run test:unit -w layers
  check-docs-snippets:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: Setup NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: ./.github/actions/cached-node-modules
      - name: Run linting
        run: npm run lint -w docs/snippets
