name: Run e2e Tests

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: '(Optional) PR Number. If you specify a value the value of the branch field will be ignored.'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  run-e2e-tests-on-utils:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
      PR_NUMBER: ${{ inputs.prNumber }}
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    strategy:
      matrix:
        package:
          [
            layers,
            packages/logger,
            packages/metrics,
            packages/tracer,
            packages/parameters,
            packages/idempotency,
          ]
        version: [16, 18, 20]
        arch: [x86_64, arm64]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      # If we pass a PR Number when triggering the workflow we will retrieve the PR info and get its headSHA
      - name: Extract PR details
        id: extract_PR_details
        if: ${{ inputs.prNumber != '' }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const script = require('.github/scripts/get_pr_info.js');
            await script({github, context, core});
      # Only if a PR Number was passed and the headSHA of the PR extracted,
      # we checkout the PR at that point in time
      - name: Checkout PR code
        if: ${{ inputs.prNumber != '' }}
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ steps.extract_PR_details.outputs.headSHA }}
      - name: Setup NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '20'
      - name: Setup dependencies
        uses: ./.github/actions/cached-node-modules
        with:
          nodeVersion: '20'
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@04b98b3f9e85f563fb061be8751a0352327246b0 # v3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: eu-west-1
          mask-aws-account-id: true
      - name: Run integration tests on utils
        env:
          RUNTIME: nodejs${{ matrix.version }}x
          CI: true
          ARCH: ${{ matrix.arch }}
          JSII_SILENCE_WARNING_DEPRECATED_NODE_VERSION: true
        run: npm run test:e2e -w ${{ matrix.package }}
